name: Check Pull Requests

on: [pull_request]

jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.1
              with:
                  node-version: 12.x

            # TODO: Need to read more why we should add this yarn cache thingy
            - name: Get yarn cache directory path
              id: yarn_cache_dir
              run: echo "::set-output name=path::$(yarn cache dir)"

            - name: Cache yarn and node_modules
              uses: actions/cache@v2
              with:
                  path: |
                      ${{ steps.yarn_cache_dir.outputs.path }}
                      node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies
              run: yarn install

            - name: Linting
              run: yarn frontend:lint
